name: pinch_zoom
description: A widget based on Flutter's new Interactive Viewer that makes picture pinch zoom, and return to its initial size and position when released.
version: 2.0.0
homepage: https://www.jelter.net

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

repository: https://github.com/tkortekaas/pinch_zoom

flutter:
